version: "3.2"
services:
  # php:
  #   build: 
  #     context: './php/'
  #     args:
  #      PHP_VERSION: ${PHP_VERSION}
  #   networks:
  #     - backend
  #   volumes:
  #     - ${PROJECT_ROOT}/:/var/www/html/
  #   # container_name: php

  # apache:
  #   build:
  #     context: './apache/'
  #     args:
  #      APACHE_VERSION: ${APACHE_VERSION}
  #   depends_on:
  #     - php
  #     - mysql
  #   networks:
  #     - frontend
  #     - backend
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ${PROJECT_ROOT}/:/var/www/html/
    # container_name: apache

  django:
    build:
      context: './django/'
    restart: always
    # command: django-admin startproject composeexample
      # sh -c "python manage.py runserver 0.0.0.0:8000
      #        && django-admin startproject composeexample"
    ports:
      - "8000:8000"
    volumes:
      # - .:/app
      - ./mysql/tmp/app/mysqld:/run/mysqld
    depends_on:
      - mysql
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - backend

  mysql:
    build:
      context: './mysql/'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/tmp/app/mysqld:/var/run/mysqld
    networks:
      - backend
    # environment:
    #   - MYSQL_DATABASE="${DB_NAME}"
    #   - MYSQL_ROOT_PASSWORD="${DB_ROOT_PASSWORD}"
    #   - MYSQL_USER="${DB_USERNAME}"
    #   - MYSQL_PASSWORD="${DB_PASSWORD}"
    container_name: db

  
networks:
  frontend:
  backend:
# volumes:
#     data:
