version: "3.2"
services:
  # php:
  #   build: 
  #     context: './php/'
  #     args:
  #      PHP_VERSION: ${PHP_VERSION}
  #   networks:
  #     - backend
  #   volumes:
  #     - ${PROJECT_ROOT}/:/var/www/html/
  #   # container_name: php

  # apache:
  #   build:
  #     context: './apache/'
  #     args:
  #      APACHE_VERSION: ${APACHE_VERSION}
  #   depends_on:
  #     - php
  #     - mysql
  #   networks:
  #     - frontend
  #     - backend
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ${PROJECT_ROOT}/:/var/www/html/
    # container_name: apache

  django:
    build:
      context: './django/'
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./mysql/tmp/app/mysqld:/run/mysqld
      - ./django/:/app
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "db:3306", "--strict", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - backend

  mysql:
    build:
      context: './mysql/'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/tmp/app/mysqld:/var/run/mysqld
    networks:
      - backend
    container_name: db

  
networks:
  frontend:
  backend:
# volumes:
#     data:
