# Generated by Django 2.0.2 on 2021-02-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieID', models.CharField(blank=True, max_length=255, null=True, verbose_name='movieID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='titlle')),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
